services:
  h2-db:
    platform: linux/x86_64
    container_name: h2
    image: oscarfonts/h2:2.1.214
    ports:
      - 1521:1521
      - 8081:81
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - ./h2/:/opt/h2-data
    restart: always
